version: "2.3"

services:
  retradio:
    container_name: retradio
    image: burgrp/retradio:latest
    privileged: true
    restart: always
    volumes:
      - "/dev:/dev"
      - "/sys:/sys"
      - "/data/retradio:/data"
    environment: 
      HTTP_PORT: "80"
      DATA_DIR: "/data"
      #DEBUG: "app:err,app:error,mplayer:err"
      DEBUG: "*"
    ports:
      - "80:80"
      - "127.0.0.7:9229:9229"
    labels:
      "farm.device.services": "80 retradio, 9229 debugger hidden"
    command: 'sh -c "alsactl init; node --inspect=0.0.0.0:9229 src/retradio.js"'
