version: "2.3"

services:
  retradio:
    container_name: retradio
    image: burgrp/retradio
    privileged: true
    restart: always
    volumes:
      - "/dev:/dev"
      - "/sys:/sys"
      - "/data/retradio:/data"
    environment: 
      HTTP_PORT: "80"
      DATA_DIR: "/data"
      #DEBUG: "*"
    ports:
      - "80:80"
    labels:
      "farm.device.service": "private retradio 80"
