FROM --platform=arm docker.io/golang:1.22.0-alpine3.19

COPY go.mod go.sum main.go /build/
WORKDIR /build

RUN go mod download

RUN apk add gcc build-base pkgconf

RUN apk add alsa-lib-dev

RUN CGO_ENABLED=1 go build

##################################

RUN apk add alpine-sdk

COPY APKBUILD /build/

RUN abuild -F checksum
RUN abuild -Fr
